#!/usr/bin/env python3
"""Controller lookup tables for maburgs, exported from devourer's Python
link/energy models (nominal calibration). SLOW (minutes): LinkModel runs its
Monte-Carlo per (mcs, snr-bucket, overhead) cell. Deterministic: link_model
seeds each cell's RNG from the cell key, so re-run + git diff must be clean.
C++ consumes the grid via lookup; Python's runtime bucketing (round to 1 dB)
is replicated on the C++ side (op_table.cpp)."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
PRECODER = os.path.abspath(os.path.join(ROOT, "..", "devourer", "tools", "precoder"))
sys.path.insert(0, PRECODER)

import energy_model as em  # noqa: E402
import link_model as lm    # noqa: E402

MCS = list(range(8))
OVERHEADS = [0.10, 0.25, 0.50, 0.75, 1.00]
SNR_LO, SNR_HI, BUCKET = -20.0, 60.0, 1.0

link = lm.LinkModel()            # nominal channels, trials=2000, 1 dB buckets
cal = em.load_calibration()      # nominal curves

n_buckets = int((SNR_HI - SNR_LO) / BUCKET) + 1
buckets = [SNR_LO + i * BUCKET for i in range(n_buckets)]
grid = []
for mcs in MCS:
    for ov in OVERHEADS:
        for snr in buckets:
            grid.append(link.p_deliver(snr, mcs, ov, sbi=True))
        print(f"mcs{mcs} ov{ov} done", file=sys.stderr)

out = os.path.join(ROOT, "gs", "src", "gen", "gen_tables.h")
os.makedirs(os.path.dirname(out), exist_ok=True)


def carr(name, vals, per_line=6):
    lines = [f"inline constexpr double {name}[] = {{"]
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(repr(v) for v in vals[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


with open(out, "w") as f:
    f.write("// GENERATED by tools/genvectors/gen_tables.py — DO NOT EDIT.\n")
    f.write("// p_deliver grid + nominal calibration from devourer's\n")
    f.write("// link_model.py / energy_model.py (sbi=True, 1 dB buckets).\n")
    f.write("#pragma once\n\nnamespace maburgs::gen {\n\n")
    f.write(f"inline constexpr double kSnrLo = {SNR_LO!r};\n")
    f.write(f"inline constexpr double kSnrBucket = {BUCKET!r};\n")
    f.write(f"inline constexpr int kSnrBuckets = {n_buckets};\n")
    f.write(f"inline constexpr int kMcsCount = {len(MCS)};\n")
    f.write("inline constexpr double kOverheads[] = {"
            + ", ".join(repr(o) for o in OVERHEADS) + "};\n")
    f.write(f"inline constexpr int kOverheadCount = {len(OVERHEADS)};\n\n")
    f.write("// [(mcs * kOverheadCount + ov_idx) * kSnrBuckets + bucket_idx]\n")
    f.write(carr("kPDeliver", grid) + "\n\n")
    f.write(carr("kTxagcGainDb", list(cal.txagc_gain_db)) + "\n\n")
    f.write(carr("kPaW", list(cal.p_pa_w)) + "\n\n")
    f.write(f"inline constexpr double kPBaselineW = {cal.p_baseline_w!r};\n")
    f.write(f"inline constexpr double kTPreUs = {cal.t_pre_us!r};\n")
    f.write("\n}  // namespace maburgs::gen\n")
print("wrote", out)
