#!/usr/bin/env python3
"""Decode an MSP OSD font atlas (indexed PNG) into a committed C++ glyph table.

Usage: gen_font.py <font.png> <out.cpp>
Emits `const maburgs::MspFont kMspFontBtfl` with premultiplied ARGB32 glyphs,
ordered by index `char | (page<<8)`. Stdlib only (no Pillow).

Atlas layout: width = glyph_w * 4 pages, height = glyph_h * 256 chars.
Glyph (char,page) occupies atlas cols [page*gw, page*gw+gw), rows
[char*gh, char*gh+gh).
"""
import sys, zlib, struct

def decode_indexed_png(path):
    d = open(path, "rb").read()
    assert d[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG"
    pos = 8; W = H = bd = ct = 0; plte = b""; trns = b""; idat = b""
    while pos < len(d):
        ln = struct.unpack(">I", d[pos:pos+4])[0]; typ = d[pos+4:pos+8]
        data = d[pos+8:pos+8+ln]; pos += 12 + ln
        if typ == b"IHDR": W, H, bd, ct = struct.unpack(">IIBB", data[:10])
        elif typ == b"PLTE": plte = data
        elif typ == b"tRNS": trns = data
        elif typ == b"IDAT": idat += data
        elif typ == b"IEND": break
    assert ct == 3 and bd == 4, "expected 4-bit indexed PNG (ct=3 bd=4), got ct=%d bd=%d" % (ct, bd)
    raw = zlib.decompress(idat)
    sb = (W * bd + 7) // 8  # scanline bytes
    def paeth(a, b, c):
        p = a + b - c; pa = abs(p-a); pb = abs(p-b); pc = abs(p-c)
        return a if pa <= pb and pa <= pc else (b if pb <= pc else c)
    out = bytearray(); prev = bytearray(sb); o = 0
    for _ in range(H):
        ft = raw[o]; o += 1; line = bytearray(raw[o:o+sb]); o += sb
        for i in range(sb):
            a = line[i-1] if i >= 1 else 0; b = prev[i]; c = prev[i-1] if i >= 1 else 0
            if ft == 1: line[i] = (line[i] + a) & 255
            elif ft == 2: line[i] = (line[i] + b) & 255
            elif ft == 3: line[i] = (line[i] + ((a + b) >> 1)) & 255
            elif ft == 4: line[i] = (line[i] + paeth(a, b, c)) & 255
        out += line; prev = line
    def index(x, y):
        byte = out[y*sb + x//2]
        return (byte >> 4) if x % 2 == 0 else (byte & 0xF)
    def rgba(i):
        r, g, b = plte[i*3], plte[i*3+1], plte[i*3+2]
        a = trns[i] if i < len(trns) else 255
        return r, g, b, a
    return W, H, index, rgba

def premult_argb(r, g, b, a):
    return (a << 24) | (((r*a)//255) << 16) | (((g*a)//255) << 8) | ((b*a)//255)

def main():
    png, out_cpp = sys.argv[1], sys.argv[2]
    W, H, index, rgba = decode_indexed_png(png)
    pages, chars = 4, 256
    gw, gh = W // pages, H // chars
    n = pages * chars
    words = []
    for ch in range(chars):
        for page in range(pages):
            for y in range(gh):
                for x in range(gw):
                    words.append(premult_argb(*rgba(index(page*gw + x, ch*gh + y))))
    with open(out_cpp, "w") as f:
        f.write('// GENERATED by tools/msp/gen_font.py from %s — do not edit.\n' % png)
        f.write('#include "msp_font.h"\nnamespace maburgs {\n')
        f.write('static const uint32_t kBtflPixels[] = {\n')
        for i in range(0, len(words), 12):
            f.write(",".join("0x%08x" % w for w in words[i:i+12]) + ",\n")
        f.write('};\n')
        f.write('const MspFont kMspFontBtfl = { %d, %d, %d, kBtflPixels };\n' % (gw, gh, n))
        f.write('}  // namespace maburgs\n')
    sys.stderr.write("wrote %s: %d glyphs %dx%d (%d words)\n" % (out_cpp, n, gw, gh, len(words)))

if __name__ == "__main__":
    main()
